questions = [
    {"question": "The Statue of Liberty was a gift from France to the United States.", "answer": "True"},
    {"question": "The Great Wall of China is visible from space.", "answer": "False"},
    {"question": "Humans have five senses.", "answer": "True"},
    {"question": "The capital of Australia is Sydney.", "answer": "False"},
    {"question": "Lightning never strikes the same place twice.", "answer": "False"},
    {"question": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"question": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"question": "Bananas grow on trees.", "answer": "False"},
    {"question": "An octopus has three hearts.", "answer": "True"},
    {"question": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"question": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"question": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"question": "Bats are blind.", "answer": "False"},
    {"question": "The smallest bone in the human body is in the ear.", "answer": "True"},
    {"question": "Sharks are mammals.", "answer": "False"},
    {"question": "Honey never spoils.", "answer": "True"},
    {"question": "The human body has four lungs.", "answer": "False"},
    {"question": "Sound travels faster in water than in air.", "answer": "True"},
    {"question": "The human nose can detect over 1 trillion different scents.", "answer": "True"},
    {"question": "Dolphins sleep with one eye open.", "answer": "True"},
    {"question": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"question": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"question": "Humans can breathe and swallow at the same time.", "answer": "False"},
    {"question": "A group of crows is called a murder.", "answer": "True"},
    {"question": "Camels have three sets of eyelids to protect themselves from blowing sand.", "answer": "True"},
    {"question": "There are 365 days in a year on Mars.", "answer": "False"},
    {"question": "Penguins can fly.", "answer": "False"},
    {"question": "Coffee beans are actually seeds.", "answer": "True"},
    {"question": "Water boils at 100 degrees Celsius.", "answer": "True"},
    {"question": "Octopuses have blue blood.", "answer": "True"},
    {"question": "Bees can recognize human faces.", "answer": "True"},
    {"question": "The Sun is a star.", "answer": "True"},
    {"question": "Polar bears have black skin.", "answer": "True"},
    {"question": "The longest river in the world is the Nile River.", "answer": "True"},
    {"question": "Humans have two sets of teeth in their lifetime.", "answer": "True"},
    {"question": "The moon is larger than the Earth.", "answer": "False"},
    {"question": "Butterflies taste with their feet.", "answer": "True"},
    {"question": "The fastest land animal is the cheetah.", "answer": "True"},
    {"question": "There are more stars in the sky than grains of sand on Earth.", "answer": "True"},
    {"question": "Ostriches can fly.", "answer": "False"},
    {"question": "The heart of a shrimp is located in its head.", "answer": "True"},
    {"question": "There are seven colors in a rainbow.", "answer": "True"},
    {"question": "Pineapples grow on trees.", "answer": "False"},
    {"question": "Humans can only use 10% of their brains.", "answer": "False"},
    {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"question": "Humans have more than five senses.", "answer": "True"},
    {"question": "An ant can lift 50 times its own weight.", "answer": "True"},
    {"question": "Bananas are berries.", "answer": "True"},
    {"question": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"question": "There are 50 states in the United States.", "answer": "True"},
    {"question": "Humans have three kidneys.", "answer": "False"},
    {"question": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"question": "The chemical symbol for gold is Au.", "answer": "True"},
    {"question": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"question": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"question": "The human body has 206 bones.", "answer": "True"},
    {"question": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False"},
    {"question": "The Nile River is the longest river in the world.", "answer": "False"},
    {"question": "The human brain stops growing after the age of 18.", "answer": "False"},
    {"question": "The Eiffel Tower is taller than the Washington Monument.", "answer": "True"},
    {"question": "The Earth has only one moon.", "answer": "True"},
    {"question": "Venus is the hottest planet in our solar system.", "answer": "True"},
    {"question": "There are 365 days in a leap year.", "answer": "False"},
    {"question": "Bees communicate with each other by dancing.", "answer": "True"},
    {"question": "Albert Einstein failed mathematics in school.", "answer": "False"},
    {"question": "Mars is known as the Red Planet.", "answer": "True"},
    {"question": "The Amazon River flows through Brazil only.", "answer": "False"},
    {"question": "Water boils at 100 degrees Fahrenheit.", "answer": "False"},
    {"question": "The human heart has four chambers.", "answer": "True"},
    {"question": "The currency of Japan is the yen.", "answer": "True"},
    {"question": "The Sahara Desert is the largest desert in the world.", "answer": "False"},
    {"question": "The moon has its own gravitational force.", "answer": "True"}
]
